services:
  webapp:
    image: webapp-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # Match the container port to the exposed port
    depends_on:
      - db


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: alien
      MYSQL_USER: hah
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
